
name: Build Flexibits
on: 
  push: 
  pull_request: 
  workflow_dispatch: 
jobs: 
  BuildFlexibits: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use PSSVG Action
        uses: StartAutomating/PSSVG@main
        id: PSSVG
      - name: BuildPipeScript
        uses: StartAutomating/PipeScript@main

